# Generated by Django 2.0.4 on 2018-05-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metro', models.URLField(blank=True, null=True)),
                ('fozi', models.URLField(blank=True, null=True)),
                ('auchan', models.URLField(blank=True, null=True)),
                ('novus', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('metro', 'metro'), ('fozi', 'fozi'), ('auchan', 'auchan'), ('novus', 'novus')], max_length=20)),
                ('price', models.IntegerField()),
                ('price_3x', models.IntegerField(blank=True, null=True)),
                ('price_6x', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='shop.Product')),
            ],
        ),
    ]
